version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: securitydb_dev
    environment:
      POSTGRES_DB: "security_dev"
      POSTGRES_USER: "garage474_dev"
      POSTGRES_PASSWORD: ""
      ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@garage474.dev"
      PGADMIN_DEFAULT_PASSWORD: ""
    ports:
      - "16543:80"
    depends_on:
      - db
  api:
    build: .
    environment:
      secret: ""
      salt: ,
      ConnectionStrings: ""
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgresql_data: